### ISSUE TITLE
Live Style with Chrome Canary

### ISSUE THREAD

**Issue by scottwio** [emmetio/livestyle-sublime-old#8]
I'm trying to use Live Style with the latest version of Chrome Canary. The pluign installs fine and works well in Standard Chrome but when I open Chrome Canary and then open dev tools with this plugin install developers tools grinds to a halt. The developer tools interface becomes completely unresponsive.

**Comment by petermac-** [comment]
I'm currently having the same issue with the beta version of Chrome - 29.0.1547.49 beta-m (about to try other versions).

**Comment by sergeche** [comment]
Looks like newer Chrome versions does not allow extensions to modify resources. Try to stick with stable Chrome for now, I’ll check out how it can be fixed

**Comment by EmilioBravo** [comment]
I can't install the extension on Chrome ver 23.0.1271.97 on ubuntu linux, but I can install it on Chromium ver 28.0.1500.71 Ubuntu 13.04 (28.0.1500.71-0ubuntu1.13.04.1)

**Comment by sergeche** [comment]
@EmilioBravo well, because Chrome 23 is too old and you should use at least ver 28

**Comment by EmilioBravo** [comment]
@sergeche you are right. I've updated to ver 28 and its working great. Thanks a lot!

**Comment by ghost** [comment]
Running Chrome 30.0.1588.0 dev-m doesn't seem to allow modification of resources. Finally got everything showing up right in ST3 and Chrome and now it won't work because I'm running a developer version of Chrome. *sigh"
Awesome tool, though! If and when I ever get it to work, I'm sure it will be a great resource to style edits without the save/refresh methods I've used so much. Got tipped by a friend on Google+, which prompted install of ST3 and all the base tools so I could use the extension... however I'm not really keen on reinstalling Chrome stable for it. We'll see if this gets fixed for later versions any time soon.

Maybe this will help... a background.html console output for the extension:
Got editor ID 
Object
files: Array[2]
icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdRI3GThRld+gbj2JwhuRFy5cZ3Ncd5LBwZCIIIXDlzmeZ9z4d458t9WoVB4XywWCcnn89i2TSaTIZvNEuRhJvtP0e7R6XT6VYJer8dkMmE0GrHf3uPxg1s8f+TR9ncZDocq63a7SiId6YogBqiPg8FASe43d3iz7/D7rcuP1zf4NnHxfV9yQc0CSFcEeihotVo0Gg22tzbh3SbP7lq4lzTuuHlqtZrkQlSgi8AIBZVKBc/zuH5lnc7tFX4OL/L9wOTJlsbGepFyuSwzUYERCqIXhGVZJJNJbqbP0b66DC8ucO/yedLptMzMF4S3X7JXeFWJ4Zln2LZPw9NT+BuxxQTquaw1Xl47yZ/WEr92j3PgnMBc08nlcvMF1Wo1DNW7G4aBpmnouo5pmtGyzM4K+v0+4/F4ITqdzqzAdV0cxyGVSsmpc5G/s1QqzQg+N5tNdUmJRIJ4PD4XkdTrdaQTClYDlvnHFXTOqu7h5mHAx4AvC/IhYE+6IliK2IwFWT3sHPsL6BnLQ4kfGmsAAAAASUVORK5CYII="
id: "st3"
title: "Sublime Text 3"
**proto**: Object
 background.js:18
7
Error in response to storage.get: TypeError: Cannot read property 'path' of null
    at r (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16512)
    at o (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16891)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:18000 background.html:1
No "inspector://www.facebook.com/inspector-stylesheet" resource in styles cache background.js:18
(anonymous function) background.js:18
4
Error in response to storage.get: TypeError: Cannot read property 'path' of null
    at r (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16512)
    at o (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16891)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:18000 background.html:1
Disconnecting devtools:2 background.js:18
Disconnecting panel:2 background.js:18
Got editor ID 
Object
files: Array[2]
icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgYCM23JjEwy+cJC41gRdTIEGyELU7BNNMJQhUBBTUjSRdRI3GThRld+gbj2JwhuRFy5cZ3Ncd5LBwZCIIIXDlzmeZ9z4d458t9WoVB4XywWCcnn89i2TSaTIZvNEuRhJvtP0e7R6XT6VYJer8dkMmE0GrHf3uPxg1s8f+TR9ncZDocq63a7SiId6YogBqiPg8FASe43d3iz7/D7rcuP1zf4NnHxfV9yQc0CSFcEeihotVo0Gg22tzbh3SbP7lq4lzTuuHlqtZrkQlSgi8AIBZVKBc/zuH5lnc7tFX4OL/L9wOTJlsbGepFyuSwzUYERCqIXhGVZJJNJbqbP0b66DC8ucO/yedLptMzMF4S3X7JXeFWJ4Zln2LZPw9NT+BuxxQTquaw1Xl47yZ/WEr92j3PgnMBc08nlcvMF1Wo1DNW7G4aBpmnouo5pmtGyzM4K+v0+4/F4ITqdzqzAdV0cxyGVSsmpc5G/s1QqzQg+N5tNdUmJRIJ4PD4XkdTrdaQTClYDlvnHFXTOqu7h5mHAx4AvC/IhYE+6IliK2IwFWT3sHPsL6BnLQ4kfGmsAAAAASUVORK5CYII="
id: "st3"
title: "Sublime Text 3"
**proto**: Object

**Comment by sergeche** [comment]
Check out v0.8.2 of Chrome extension, it works on my Canary 32 setup
